# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CIV
email: email@email.com
description: > # this means to ignore newlines until "baseurl:"
  CIV
# baseurl: "" # the subpath of your site, e.g. /blog
baseurl: "/s/civ"
url: "" # the base hostname & protocol for your site
# twitter_username: layerland
# github_username:  layerland

# Build settings
markdown: kramdown
exclude: [node_modules, bower_components,bower.json, gulpfile.js]
# sass:
#   style: compressed
# gems:
#     - jekyll-minifier
